name: Deploy Odoo 17

on:
  push:
    branches:
      - main # or your default branch name
  workflow_dispatch: # Allows manual trigger

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: SSH into server and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          script: |
            # Navigate to your Odoo directory
            cd /home/odoo-pipline

            # Pull the latest changes
            git pull origin main

            # Restart the Docker container
            docker restart stupefied_chatelet  # Replace with your container name

            # Optional: Check container status
            docker ps | grep stupefied_chatelet
