name: Deploy Odoo 17

on:
  push:
    branches:
      - main  # or your default branch name
  workflow_dispatch:  # Allows manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: SSH into server and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            # Navigate to your Odoo directory
            cd /path/to/your/odoo
            
            # Pull the latest changes
            git pull origin main
            
            # Restart the Docker container
            docker restart odoo_container  # Replace with your container name
            
            # Optional: Check container status
            docker ps | grep odoo_container
